DROP SCHEMA public CASCADE;
CREATE SCHEMA public;


CREATE TABLE "Employees"
(
	branch_id 			VARCHAR(15) NOT NULL,
    id 					INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	first_name	 		VARCHAR(15) NOT NULL,
	middle_name	 		VARCHAR(15),
	first_surname	 	VARCHAR(15) NOT NULL,
	second_surname	 	VARCHAR(15) NOT NULL,
	birth_date		 	DATE NOT NULL,
    phone_number 		VARCHAR(15) NOT NULL,
	username			VARCHAR(15) NOT NULL,
	password			VARCHAR(15) NOT NULL,
	age				INT NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE "Clients"
(
	id 					INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	first_name 			VARCHAR(15) NOT NULL,
	middle_name 		VARCHAR(15),
	first_surname 		VARCHAR(15) NOT NULL,
	second_surname 		VARCHAR(15) NOT NULL,
	birth_date 			DATE NOT NULL,
	phone_number 		VARCHAR(15),
	username 			VARCHAR(15) NOT NULL,
	password 			VARCHAR(15) NOT NULL,
	PRIMARY KEY (id)
);


CREATE TABLE "Branches"
(
    cinema_name VARCHAR(15) NOT NULL,
    province VARCHAR(15) NOT NULL,
    district VARCHAR(15) NOT NULL,
    room_quantity INT NOT NULL,
    PRIMARY KEY(cinema_name)
);


CREATE TABLE "Rooms"
(
	branch_name 		VARCHAR(15) NOT NULL,
    id 					INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	row_quantity 		INT NOT NULL,
	column_quantity 	INT NOT NULL,
    capacity 			INT NOT NULL,	
	PRIMARY KEY(id)
);


CREATE TABLE "Seats"
(
	room_id 			INT NOT NULL,
    number 				INT NOT NULL,
	status		 		VARCHAR(15) NOT NULL,
	PRIMARY KEY(room_id),
	UNIQUE(number)
);

CREATE TABLE "Bills"
(
	client_id 			INT NOT NULL,
    projection_id 		INT NOT NULL,
	id					INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	detail				VARCHAR(255),
	PRIMARY KEY(id)
);

CREATE TABLE "Projections"
(
	room_id 			INT NOT NULL,
    movie_id	 		INT NOT NULL,
	id					INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	date				DATE NOT NULL,
	time				TIME NOT NULL,
	PRIMARY KEY(id)
);


CREATE TABLE "Movies"
(
	id 						INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	classification_id 		VARCHAR(15),
	director_id 				INT,
    image 					VARCHAR(15) NOT NULL,
    original_name 			VARCHAR(15) NOT NULL,
    name 					VARCHAR(15) NULL,
	length 					VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE "Directors"
(
	id				INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	name 			VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE "Classifications"
(
	code 			VARCHAR(15) NOT NULL UNIQUE,
	details 		VARCHAR(15) NOT NULL,
	age_rating		INT NOT NULL,
    PRIMARY KEY(code)
);


CREATE TABLE "Acts"
(
	movie_id		INT NOT NULL,
	actor_id		INT NOT NULL
);


CREATE TABLE "Actors"
(
	id				INT NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 999 CACHE 1 ),
	name 			VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)
);



-- Foreign Keys

ALTER TABLE "Employees"
ADD CONSTRAINT EMPLOYEE_BRANCH_FK FOREIGN KEY(branch_id)
REFERENCES "Branches"(cinema_name);


ALTER TABLE "Rooms"
ADD CONSTRAINT ROOM_BRANCH_FK FOREIGN KEY(branch_name)
REFERENCES "Branches"(cinema_name);


ALTER TABLE "Seats"
ADD CONSTRAINT SEAT_ROOM_FK FOREIGN KEY(room_id)
REFERENCES "Rooms"(id);


ALTER TABLE "Bills"
ADD CONSTRAINT BILL_CLIENT_FK FOREIGN KEY(client_id)
REFERENCES "Clients"(id);

ALTER TABLE "Bills"
ADD CONSTRAINT BILL_PROJECTION_FK FOREIGN KEY(projection_id)
REFERENCES "Projections"(id);


ALTER TABLE "Projections"
ADD CONSTRAINT PROJECTION_ROOM_FK FOREIGN KEY(room_id)
REFERENCES "Rooms"(id);

ALTER TABLE "Projections"
ADD CONSTRAINT PROJECTION_MOVIE_FK FOREIGN KEY(movie_id)
REFERENCES "Movies"(id);


ALTER TABLE "Movies"
ADD CONSTRAINT MOVIE_CLASSIFICATION_FK FOREIGN KEY(director_id)
REFERENCES "Directors"(id);

ALTER TABLE "Movies"
ADD CONSTRAINT MOVIE_DIRECTOR_FK FOREIGN KEY(classification_id)
REFERENCES "Classifications"(code);


ALTER TABLE "Acts"
ADD CONSTRAINT ACTS_MOVIE_FK FOREIGN KEY(movie_id)
REFERENCES "Movies"(id);

ALTER TABLE "Acts"
ADD CONSTRAINT ACTS_ACTOR_FK FOREIGN KEY(actor_id)
REFERENCES "Actors"(id);



